# Generated by Django 3.2.3 on 2022-05-28 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
