# Generated by Django 3.2.3 on 2022-05-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_rename_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(null=True, upload_to='Main/static/videos'),
        ),
    ]
